org: kunalverma2468
app: serverless-docuconvo-app
service: serverless-docuconvo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
